name: Lines of Code Changed

on:
  # Schedule updates at minute 0 past every 12th hour
  schedule:
    - cron: "0 */12 * * *"
  # Manual trigger via UI
  workflow_dispatch:
  # Also run on pushes to specified branches
  push:
    branches:
      - master
      - main
      - metrics

jobs:
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        # Docker is preinstalled on Ubuntu runners, so only jq is needed
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Allow custom token usage for PR creation

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.code.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_skipped: testing, The-Futurists_Manthan_Frontend
          plugin_lines_repositories_limit: 4

      - name: Create PR branch and commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b metrics-update
          git add assets/metrics.plugin.code.lines.svg
          git commit -m "chore: update metrics"
          git push origin metrics-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update metrics"
          branch: metrics-update
          title: "Update metrics SVG"
          body: "Auto-generated lines of code metrics."
