name: Leetcode Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure dependencies are installed
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      # Step 3: Set up Metrics variables
      - name: Set up environment
        env:
          METRICS_ACTION: "leetcode"
          METRICS_ACTION_PATH: "./metrics"
          METRICS_TAG: "latest"
        run: |
          echo "GitHub action: $METRICS_ACTION ($METRICS_ACTION_PATH)"
          cd $METRICS_ACTION_PATH

          # Check for missing dependencies
          MISSING_DEPENDENCIES=0
          for DEPENDENCY in docker jq; do
            if ! which $DEPENDENCY > /dev/null 2>&1; then
              echo "::error::\"$DEPENDENCY\" is not installed on the runner."
              MISSING_DEPENDENCIES=1
            fi
          done

          if [[ $MISSING_DEPENDENCIES == "1" ]]; then
            echo "Runner compatibility: missing dependencies"
            exit 1
          else
            echo "Runner compatibility: compatible"
          fi

      # Step 4: Pull or build Docker image
      - name: Pull or build Docker image
        env:
          METRICS_IMAGE: "ghcr.io/lowlighter/metrics:${{ env.METRICS_TAG }}"
        run: |
          echo "Using pre-built version $METRICS_TAG, will pull Docker image from GitHub registry"
          if ! docker pull $METRICS_IMAGE; then
            echo "Failed to fetch Docker image from GitHub registry, will rebuild it locally"
            METRICS_IMAGE="metrics:local"
            docker build -t $METRICS_IMAGE .
          fi

      # Step 5: Run the script
      - name: Run metrics script
        run: |
          docker run --rm $METRICS_IMAGE

      # Step 6: Commit changes through a pull request
      - name: Create Pull Request for Changes
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update metrics
          branch: metrics-update
          title: Metrics Update
          body: |
            This pull request contains updated metrics generated by the workflow.