name: Lines of Code Changed

on:
  schedule:
    # Run at minute 0 past every 12th hour
    - cron: "0 */12 * * *"
  # Manual trigger
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - metrics

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # needed for full history
          persist-credentials: false  # use custom token for pushes

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq

      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.code.lines.svg
          token: ${{ secrets.GITHUB_TOKEN }}        # use built-in token to avoid null refs
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_skipped: testing, The-Futurists_Manthan_Frontend
          plugin_lines_repositories_limit: 4

      - name: Commit and push metrics update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b metrics-update
          git add assets/metrics.plugin.code.lines.svg
          git commit -m "chore: update metrics"
          git push origin metrics-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: metrics-update
          title: "chore: update metrics SVG"
          body: "Auto-generated lines of code metrics."
