name: Languages Activity
on:
  # Schedule updates (At minute 0 past every 12th hour)
  schedule: [{ cron: "0 */12 * * *" }]
  # Lines below let you run workflow manually with each commit
  workflow_dispatch:
  push: { branches: ["master", "main", "metrics"] }
jobs:
  # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
  language-activity-metrics:
    runs-on: ubuntu-latest
    steps:
      # Install missing dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io jq

      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.languages.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage # Note that lines is only available when plugin_languages_indepth is enabled
          plugin_languages_limit: 6   # limit is 8
          plugin_languages_analysis_timeout: 15

      # Create Pull Request for updates
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-metrics
          commit-message: "Update metrics data"
          title: "Update metrics data"
          body: "This pull request updates the metrics data."
          token: ${{ secrets.GITHUB_TOKEN }}
