name: LeetCode Metrics

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and jq
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get autoremove -y || true
          sudo apt-get install -y docker.io jq
          sudo systemctl enable docker
          sudo systemctl start docker
          docker --version
          jq --version

      - name: Generate LeetCode metrics and upload to Gist
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIST }}  # Your PAT with gist scope
          committer_token: ${{ secrets.GIST }}
          committer_gist: 549db21ce1afaffa48994d7500d3d80b

          # Main config
          user: iamAntimPal
          filename: metrics.plugin.leetcode.svg
          base: ""  # No GitHub info, just plugins
          config_timezone: Asia/Kolkata

          # LeetCode plugin
          plugin_leetcode: yes
          plugin_leetcode_user: antim_pal
          plugin_leetcode_sections: solved, skills, recent
