name: LeetCode Metrics

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get install -y docker.io jq
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Generate LeetCode metrics and upload to Gist
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIST }}
          committer_token: ${{ secrets.GIST }}
          committer_gist: 549db21ce1afaffa48994d7500d3d80b

          # General config
          user: iamAntimPal
          filename: metrics.plugin.leetcode.svg
          base: ""

          # LeetCode plugin
          config_timezone: Asia/Kolkata
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
