# .github/workflows/repository-metrics.yml
name: Repository Metrics
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  generate-repo-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and jq
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd containerd.io || true
          sudo apt-get autoremove -y || true
          sudo apt-get install -y docker.io jq
          sudo systemctl enable docker
          sudo systemctl start docker
          docker --version
          jq --version

      - name: Generate and upload repository metrics to Gist
        uses: lowlighter/metrics@latest
        with:
          # Authentication
          token: ${{ secrets.GIST }}           # Personal Access Token with gist scope
          committer_token: ${{ secrets.GIST }} # Required for uploading to Gist
          committer_gist: 549db21ce1afaffa48994d7500d3d80b

          # General configuration
          user: iamAntimPal
          filename: metrics.plugin.repositories.svg
          base: ""                              # No header

          # Repositories plugin
          repositories: yes
          repositories_forks: yes               # Include forks if needed
          repositories_affiliations: owner, collaborator
          repositories_limit: 5                # Limit repositories displayed

          # Featured repository
          repositories_batch: iamAntimPal/MyGithubMaster

          # Output configuration
          output_action: gist

          # Optional debug mode
          config_animations: yes
